#############################################################################
#
#                   Copyright (C) 1996 SciTech Software.
#                           All rights reserved.
#
# Descripton:   Makefile for the font converter to convert MGL 1.x fonts
#				to Windows 2.x fonts.
#
#############################################################################

CFLAGS	+= -I..

all: fntcvt$E mklib$E

fntcvt$E: fntcvt$O
mklib$E: mklib$O

.INCLUDE: "$(SCITECH)/makedefs/common.mk"
