############################################################################
#
#               Copyright (C) 1991-1997 SciTech Software, Inc.
#                            All rights reserved.
#
# Descripton:   Makefile for the HELLO program. Requires the SciTech
#               Software makefile definitions package to be installed.
#
# $Date:   01 Oct 1997 03:10:54  $ $Author:   KendallB  $
#
#############################################################################

.INCLUDE: "../common.mak"

EXELIBS         = $(BASELIBS)
USE_CXX_LINKER	:= 1

filedlg$E: filedlg$O

DEPEND_OBJ      = filedlg$O

# Define the list of object files to create dependency information for

.INCLUDE: "$(SCITECH)/makedefs/common.mk"


