#############################################################################
#
#               Copyright (C) 1991-1997 SciTech Software, Inc.
#                            All rights reserved.
#
# Descripton:   Makefile for the WMGLDOG example. Requires the SciTech
#               Software makefile definitions package to be installed.
#
# $Date:   01 Oct 1997 03:13:12  $ $Author:   KendallB  $
#
#############################################################################

.INCLUDE: "..\common.mak"

OBJECTS         = wmgldog$O wmgldog$R
EXELIBS         = $(BASELIBS)

wmgldog$E: $(OBJECTS)

DEPEND_OBJ      = $(OBJECTS)

.INCLUDE: "$(SCITECH)\makedefs\common.mk"


