#############################################################################
#
#               Copyright (C) 1991-1997 SciTech Software, Inc.
#                            All rights reserved.
#
# Descripton:   Makefile for the XMGLDOG example. Requires the SciTech
#               Software makefile definitions package to be installed.
#
# $Date:   01 Oct 1997 03:13:12  $ $Author:  StephaneP  $
#
#############################################################################

.INCLUDE: "../common.mak"

OBJECTS         = xmgldog$O
EXELIBS         = $(BASELIBS) -lXpm

xmgldog$E: $(OBJECTS)

DEPEND_OBJ      = $(OBJECTS)

.INCLUDE: "$(SCITECH)/makedefs/common.mk"


