############################################################################
#
#               Copyright (C) 1991-1997 SciTech Software, Inc.
#                            All rights reserved.
#
# Descripton:   Makefile for sample programs. Requires the SciTech
#               Software makefile definitions package to be installed.
#
#############################################################################

.INCLUDE: "../common.mak"

EXELIBS		= $(BASELIBS)

all: hello$E direct$E

hello$E:    hello$O
direct$E:   direct$O

.INCLUDE: "$(SCITECH)/makedefs/common.mk"

