#############################################################################
#
#               Copyright (C) 1991-1997 SciTech Software, Inc.
#                            All rights reserved.
#
# Descripton:   Makefile for the PHMGLDOG example. Requires the SciTech
#               Software makefile definitions package to be installed.
#
# $Date:   01 Oct 1997 03:13:12  $ $Author:   KendallB  $
#
#############################################################################

.INCLUDE: "../common.mak"

OBJECTS         = phmgldog$O
EXELIBS         = $(BASELIBS) -lphoton_s

phmgldog$E: $(OBJECTS)

DEPEND_OBJ      = $(OBJECTS)

.INCLUDE: "$(SCITECH)/makedefs/common.mk"


